project:
  type: website

website:
  title: "Sample Match Dashboard"
  navbar:
    left:
      - href: single-football-match-dashboard.qmd
        text: Match Dashboard

format:
  html:
    theme: [darkly, custom.scss]
    toc: true



