project:
  type: website

website:
  title: "single-football-match-dashboard"
  navbar:
    left:
      - href: single-football-match-dashboard.qmd
        text: Match Dashboard

format:
  html:
    theme: [darkly, custom.scss]
    toc: true



